In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import numpy as np
import os
from time import time
import ML
ML.showAllVariables()
ML.init()
Sess = ML.limitGPUByGrowth()


['/cpu:0', '/gpu:0']


In [2]:
w = tf.Variable(tf.random_normal([3,2])) #隨機產生3*2的tensor
X = tf.Variable(tf.random_normal([1,3])) #隨機產生1*3的tensor

b = tf.Variable(tf.random_normal([1,2])) #隨機產生1*2的tensor
y = tf.nn.relu(tf.matmul(X,w)+b)

ts_norm = tf.Variable(tf.random_normal([1000]))
with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (w,X,b,y) = sess.run((w,X,b,y)) #一次取得所有隨機分布變數
    
    print('w : ',w)
    print('X : ',X)
    print('b : ',b)
    print('y : ',y)
    
    norm_data = ts_norm.eval()
    print(norm_data[:5])

import matplotlib.pyplot as plt
plt.hist(norm_data)
plt.show()

w :  [[ 0.60723716 -0.72217906]
 [ 0.13419233 -0.7084074 ]
 [-2.181187    0.17033528]]
X :  [[ 0.22946116 -0.08587574  0.1430427 ]]
b :  [[-0.34771737  0.10832242]]
y :  [[0.        0.0278106]]
[-1.2319295   2.1092873   0.73041975 -0.9815725  -2.1841202 ]


(array([  7.,  25.,  69., 188., 238., 217., 156.,  68.,  27.,   5.]),
 array([-2.9925189 , -2.37349792, -1.75447693, -1.13545594, -0.51643496,
         0.10258603,  0.72160702,  1.340628  ,  1.95964899,  2.57866998,
         3.19769096]),
 <a list of 10 Patch objects>)

<Figure size 640x480 with 1 Axes>

In [3]:
w = tf.Variable(tf.random_normal([3,2],dtype=tf.float64)) #隨機產生3*2的tensor
X = tf.placeholder(tf.float64,[None,3]) #預備傳入一個 n*3 的矩陣

b = tf.Variable(tf.random_normal([1,2],dtype=tf.float64)) #隨機產生1*2的tensor
y = tf.nn.relu(tf.matmul(X,w)+b) #3*2 +1*2

with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    X_Place = np.array([[0.4,0.2,0.4],
                       [0.3,0.4,0.5],
                       [0.3,-0.4,0.5]]) # 設定欲傳入3*3的矩陣
    sess.run(init)
    (w,X,b,y) = sess.run((w,X,b,y),feed_dict={X:X_Place}) #一次取得所有隨機分布變數
    
    
    print('w*X : ',sess.run(tf.matmul(X,w)))
    print('b : ',b)
    print('y : ',y)    
    

w*X :  [[ 0.56190662 -0.35342253]
 [ 0.62789855 -0.43941522]
 [ 0.75170426 -0.0577053 ]]
b :  [[1.97840557 0.50973956]]
y :  [[2.54031219 0.15631703]
 [2.60630412 0.07032434]
 [2.73010983 0.45203427]]


In [7]:
def layer(output_dim,input_dim,inputs,activation=None): #建立兩層神經網路的函數
    W = tf.Variable(tf.random_normal([input_dim,output_dim])) #以隨機分布的權重weight   
    b = tf.Variable(tf.random_normal([1,output_dim])) #以隨機分布的偏差bias
    y = tf.matmul(inputs,W) + b   # inputs = X = 輸入的二維Placeholder
    if activation == None:
        outputs = y
    else:
        outputs = activation(y) # activation:傳入的激活函數
    return outputs

X = tf.placeholder(tf.float32,[None,4]) #預備傳入一個 n*4 的矩陣
h = layer(input_dim=4,output_dim=3,inputs=X,activation=tf.nn.relu)
y = layer(input_dim=3,output_dim=2,inputs=h)
with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = [[0.4,0.2,0.4,0.5]] # 設定欲傳入1*4的張量
    (layer_X,layer_h,layer_y) = sess.run((X,h,y),feed_dict={X:X_array})
    print('input layer X : ',layer_X)
    print('hidden layer h : ',layer_h)
    print('output layer y : ',layer_y)

input layer X :  [[0.4 0.2 0.4 0.5]]
hidden layer h :  [[0.        0.        0.5470586]]
output layer y :  [[ 0.14205307 -0.12861785]]


In [16]:
def layer(output_dim,input_dim,inputs,activation=None): #建立兩層神經網路的函數
    W = tf.Variable(tf.random_normal([input_dim,output_dim])) #以隨機分布的權重weight   
    b = tf.Variable(tf.random_normal([1,output_dim])) #以隨機分布的偏差bias
    y = tf.matmul(inputs,W) + b   # inputs = X = 輸入的二維Placeholder
    if activation == None:
        outputs = y
    else:
        outputs = activation(y) # activation:傳入的激活函數
    return outputs,W,b

X = tf.placeholder(tf.float32,[None,4]) #預備傳入一個 n*4 的矩陣
h,W1,b1 = layer(input_dim=4,output_dim=3,inputs=X,activation=tf.nn.relu)
y,W2,b2 = layer(input_dim=3,output_dim=2,inputs=h)
with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = [[0.4,0.2,0.4,0.5]] # 設定欲傳入1*4的張量
    (layer_X,layer_h,layer_y,W1,W2,b1,b2) = sess.run((X,h,y,W1,W2,b1,b2),feed_dict={X:X_array})
    print('input layer X : ',layer_X ,"\n")
    print('hidden layer h : ',layer_h,"\nW1 : ", W1,"\nb1 : ",b1,"\n")
    print('output layer y : ',layer_y,"\nW2 : ", W2,"\nb2 : ",b2)

input layer X :  [[0.4 0.2 0.4 0.5]] 

hidden layer h :  [[1.1533617 0.        0.       ]] 
W1 :  [[ 0.5922188   0.25474983  0.10478781]
 [ 1.2748152  -1.7732375   0.19224627]
 [ 0.64803505 -0.84489757  1.2307391 ]
 [ 1.6979189   0.9754334  -1.7246691 ]] 
b1 :  [[-0.44666228 -0.5114812  -0.36872932]] 

output layer y :  [[ 2.759932  -1.9069697]] 
W2 :  [[ 1.1513695  -0.56502783]
 [ 0.20108788  0.7066875 ]
 [ 1.2040243  -1.0962665 ]] 
b2 :  [[ 1.4319868 -1.2552882]]
